"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowUpRight, ArrowRight, Code2, Database, Terminal, Menu, X, Sparkles, GraduationCap, Mail, Check, Copy, Send, MoveUpRight, Plus, Globe2, Layers } from "lucide-react";
import type { PublicProject, PublicSkill } from "@/lib/content";
import type { SiteContent } from "@/lib/defaults";
import { Icon, Lines, Rich } from "./content-bits";
import MotionDetails from "./motion-details";

function Asterisk({ className = "" }: { className?: string }) {
  return <svg className={className} viewBox="0 0 100 100" fill="none" aria-hidden="true">{[0, 45, 90, 135].map(angle => <path key={angle} d="M50 5V95" stroke="currentColor" strokeWidth="17" transform={`rotate(${angle} 50 50)`} />)}</svg>;
}
function Preview({ type }: { type: string }) {
  return <div className={`mockup ${type}`} aria-hidden="true"><div className="mock-top"><strong>{type === "campus" ? "c. campus" : type === "expense" ? "pennywise®" : "learnspace✳"}</strong><span>Overview <span className="mock-avatar">A</span></span></div><div className="mock-content"><div className="mock-sidebar"><Layers /><Globe2 /><Code2 /><span className="sidebar-bottom">✳</span></div><div className="mock-main"><small>{type === "campus" ? "YOUR CAMPUS. YOUR PEOPLE." : type === "expense" ? "A LITTLE CLARITY GOES A LONG WAY" : "MAKE A LITTLE ROOM FOR GROWTH"}</small><h4>{type === "campus" ? "Good things happen together." : type === "expense" ? "Your money, in perspective." : "Hello, curious mind."}</h4>{type === "expense" ? <><div className="balance"><span>Total balance</span>₹12,450<small>↗ 12.8% this month</small></div><div className="bars">{[35, 58, 42, 76, 54, 88, 68, 95, 64, 80, 55, 73].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-axis"><span>MON</span><span>TUE</span><span>WED</span><span>THU</span><span>FRI</span></div></> : <><div className="mock-banner"><div><small>{type === "campus" ? "ON THE NOTICEBOARD" : "YOUR NEXT CHAPTER"}</small><b>{type === "campus" ? <>Find your people.<br />Make your mark.</> : <>Big ideas.<br />Small beginnings.</>}</b><span>{type === "campus" ? "Explore communities ↗" : "Explore your courses ↗"}</span></div><Asterisk /></div><div className="mock-tiles"><div><span>{type === "campus" ? "01 / WHAT’S ON" : "01 / IN PROGRESS"}</span><b>{type === "campus" ? "Design & build" : "The web, explained"}</b><small>{type === "campus" ? "Connect. Create. Collaborate." : "Chapter 04 · Keep going"}</small></div><div><span>{type === "campus" ? "02 / GET TOGETHER" : "02 / THIS WEEK"}</span><b>{type === "campus" ? "Find your circle" : "A little better, daily"}</b><small>{type === "campus" ? "A space to belong." : "Your learning streak: 5 days"}</small></div></div></>}</div></div></div>;
}
function Playground() {
  const [burst, setBurst] = useState(0);
  return <div className="hero-art" data-burst={burst % 2}><div className="art-top"><span><i /> Code. Create. Improve.</span></div><div className="art-grid" /><button className="sculpture-button" onClick={() => setBurst(value => value + 1)} aria-label="Change sculpture color" aria-pressed={burst % 2 === 1}><div className="sculpture-stage"><div className="sculpture">{Array.from({ length: 12 }, (_, i) => <div className="sculpture-ring" key={i} style={{ transform: `rotateY(${i * 15}deg)` }} />)}</div><div className="sculpture-center"><Asterisk /></div></div></button><div className="code-note"><div><i /><i /><i /><span>mindset.js</span></div><code><span>const</span> ankita = &#123;<br />&nbsp; curiosity: <b>Infinity</b>,<br />&nbsp; mode: <em>"always building"</em><br />&#125;;</code></div><div className="art-bottom"><span>Click to change color <ArrowUpRight size={16} /></span></div></div>;
}
export default function Home({ content, projects, skills }: { content: SiteContent; projects: PublicProject[]; skills: PublicSkill[] }) {
  const profile = content.profile;
  const [menu, setMenu] = useState(false), [filter, setFilter] = useState("All work"), [selected, setSelected] = useState<typeof projects[number] | null>(null), [copied, setCopied] = useState(false), [status, setStatus] = useState(""), [sending, setSending] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null), trigger = useRef<HTMLButtonElement | null>(null);
  useEffect(() => { if (selected && !dialog.current?.open) dialog.current?.showModal(); }, [selected]);
  useEffect(() => { if (!menu) return; const key = (event: KeyboardEvent) => { if (event.key === "Escape") { setMenu(false); document.getElementById("menu-toggle")?.focus(); } }; const resize = () => { if (window.innerWidth > 760) setMenu(false); }; window.addEventListener("keydown", key); window.addEventListener("resize", resize); return () => { window.removeEventListener("keydown", key); window.removeEventListener("resize", resize); }; }, [menu]);
  function close() { dialog.current?.close(); setSelected(null); trigger.current?.focus(); }
  async function copy() { try { await navigator.clipboard.writeText(profile.email); setCopied(true); setTimeout(() => setCopied(false), 2200); } catch { setStatus("You can select and copy the email address above."); } }
  function offlineFallback(payload: { name: string; email: string; message: string }) {
    if (profile.email) {
      window.location.href = `mailto:${profile.email}?subject=${encodeURIComponent(`Portfolio enquiry from ${payload.name}`)}&body=${encodeURIComponent(`${payload.message}

From: ${payload.name}
Email: ${payload.email}`)}`; setStatus("The message could not reach the server, so your email app has opened instead. Send it from there to complete your enquiry."); return;
    }
    const draft = `To: Ankita
From: ${payload.name} <${payload.email}>

${payload.message}`; const url = URL.createObjectURL(new Blob([draft], { type: "text/plain;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "hello-ankita.txt"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
    setStatus("The message could not reach the server, so it was downloaded as a draft. It has not been sent.");
  }
  async function send(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget, data = new FormData(form);
    const payload = { name: String(data.get("name") || ""), email: String(data.get("email") || ""), message: String(data.get("message") || ""), company: String(data.get("company") || "") };
    setSending(true); setStatus("Sending your message…");
    try {
      const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const body = await response.json().catch(() => null);
      if (response.ok) { form.reset(); setStatus("Thank you — your message is with Ankita. She’ll reply to the email address you gave."); return; }
      if (response.status >= 500 || response.status === 503) { offlineFallback(payload); return; }
      const firstIssue = body?.details ? Object.values(body.details)[0] as string : "";
      setStatus(firstIssue || body?.error || "Your message could not be sent. Please try again.");
    } catch {
      offlineFallback(payload);
    } finally { setSending(false); }
  }
  // Filters follow whatever categories the projects actually use, so a
  // category added in the admin shows up here without a code change.
  const filters = ["All work", ...Array.from(new Set(projects.map(project => project.category).filter(Boolean)))];
  const visibleProjects = projects.filter(project => filter === "All work" || project.category === filter);
  return <><MotionDetails /><a className="skip" href="#main">Skip to content</a><header className="header"><a href="#" className="brand" aria-label={`${profile.name} home`}>{(profile.name || "ankita").toLowerCase()}<Asterisk /></a><nav id="main-nav" aria-label="Main navigation" className={menu ? "nav open" : "nav"}>{[["Work", "projects"], ["About", "about"], ["Toolkit", "skills"], ["Journey", "journey"]].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}</nav><a className="nav-contact" href="#contact" onClick={() => setMenu(false)}>Let’s talk <ArrowUpRight size={16} /></a><button id="menu-toggle" className="menu-button" aria-controls="main-nav" aria-label={menu ? "Close navigation" : "Open navigation"} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></header>
    <main id="main"><section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="status-dot" /> {content.hero.eyebrow}</div><h1><Lines text={content.hero.headline} />{content.hero.headlineAccent && <><br /><span className="heart-word">{content.hero.headlineAccent}</span></>}</h1><p>{content.hero.intro}</p><div className="hero-buttons"><a href="#projects" className="button primary">{content.hero.primaryCta} <ArrowUpRight size={19} /></a><a href="#about" className="text-button">{content.hero.secondaryCta} <ArrowRight size={17} /></a></div>{content.hero.foot && <div className="hero-foot"><GraduationCap size={20} /><span>{content.hero.foot}</span></div>}</div><div className="hero-visual"><Playground /></div></section>
      {content.focus.length > 0 && <div className="focus-strip wrap">{content.focus.map((item, i) => <span key={i}><Icon name={item.icon} /> {item.text}</span>)}</div>}
      <section className="section wrap" id="projects"><div className="section-label"><span>{content.work.label}</span></div><div className="section-heading"><h2><Lines text={content.work.heading} /> <span className="serif">{content.work.headingAccent}</span></h2><p>{content.work.intro}</p></div><div className="project-toolbar"><div className="filters" aria-label="Filter projects">{filters.map(item => <button key={item} className={filter === item ? "active" : ""} aria-pressed={filter === item} onClick={() => setFilter(item)}>{item}{item === "All work" && <span>{String(projects.length).padStart(2, "0")}</span>}</button>)}</div><span className="project-count" role="status">{visibleProjects.length} {visibleProjects.length === 1 ? "exploration" : "explorations"}</span></div><div className={`project-grid ${filter === "All work" ? "is-overview" : "is-filtered"}`} key={filter}>{visibleProjects.map((project, index) => <article className="project-card" key={project.id}><button className={`project-image ${project.color}`} aria-label={`Explore ${project.name} concept`} onClick={event => { trigger.current = event.currentTarget; setSelected(project); }}><div className="project-image-top"><span>{project.category}</span><span>Concept study</span></div><Preview type={project.id} /><span className="project-open"><ArrowUpRight size={23} /></span></button><div className="project-info"><span className="project-kicker">{index === 0 ? "Featured exploration" : project.category}</span><div className="project-title"><h3>{project.name}</h3></div><p>{project.subtitle}</p><p className="project-summary">{project.description}</p><div className="tags">{project.stack.map(item => <span key={item}>{item}</span>)}</div><button type="button" className="project-details" aria-label={`View ${project.name} details`} onClick={event => { trigger.current = event.currentTarget; setSelected(project); }}>View details <ArrowUpRight size={18} /></button></div></article>)}</div>{content.work.note && <div className="projects-note"><p>{content.work.note}</p></div>}</section>
      <section className="about-section" id="about"><div className="wrap section"><div className="section-label"><span>{content.about.label}</span></div><div className="about-grid"><div className="about-title"><h2><Lines text={content.about.heading} /><br /><span className="serif">{content.about.headingAccent}</span></h2><div className="working-style"><p className="working-label">{content.about.workingLabel}</p>{content.about.steps.map((step, i) => <div className="working-step" key={i}><span>{step.number}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></div>)}</div></div><div className="about-copy">{content.about.paragraphs.map((paragraph, i) => <p key={i}><Rich text={paragraph} /></p>)}<div className="about-notes">{content.about.notes.map((note, i) => <span key={i}><Icon name={note.icon} size={18} /> {note.text}</span>)}</div></div></div></div></section>
      <section className="section wrap" id="skills"><div className="section-label"><span>{content.skills.label}</span></div><div className="section-heading"><h2><Lines text={content.skills.heading} /> <span className="serif">{content.skills.headingAccent}</span></h2><p>{content.skills.intro}</p></div><div className="skills-grid">{skills.map((skill, i) => <article className="skill-card" key={skill.title + i}><div className="skill-top"><Icon name={skill.icon} size={24} /><span>{String(i + 1).padStart(2, "0")}</span></div><h3>{skill.title}</h3><p>{skill.text}</p><div className="tags">{skill.items.map(item => <span key={item}>{item}</span>)}</div></article>)}</div>{content.skills.note && <div className="toolkit-note"><Plus size={15} /><span>{content.skills.note}</span></div>}</section>
      <section className="journey-section" id="journey"><div className="section wrap journey-grid"><div><div className="section-label">{content.journey.label}</div><h2><Lines text={content.journey.heading} /><br /><span className="serif">{content.journey.headingAccent}</span></h2><p><Lines text={content.journey.intro} /></p></div><div className="timeline">{content.journey.steps.map((step, i) => <article key={i}><span className="timeline-dot" /><div className="timeline-meta"><small>{step.label}</small>{step.badge && <span>{step.badge}</span>}</div><h3>{step.title}</h3><p>{i === 0 && profile.college ? profile.college : step.text}</p></article>)}</div></div></section>
      <section className="contact-section section wrap" id="contact"><div className="contact-card"><div className="section-label"><span>{content.contact.label}</span></div><div className="contact-heading"><h2><Lines text={content.contact.heading} /><br /><span className="serif">{content.contact.headingAccent}</span></h2><a className="contact-arrow" href="#message-form" aria-label="Start a conversation"><MoveUpRight /></a></div><div className="contact-bottom"><p><Lines text={content.contact.intro} /></p>{profile.email ? <div className="contact-actions"><a className="button primary" href={`mailto:${profile.email}`}>Say hello <Mail size={18} /></a><button className="copy-button" onClick={copy}>{copied ? <Check size={15} /> : <Copy size={15} />} {copied ? "Copied!" : profile.email}</button></div> : <a className="text-button" href="#message-form">Start a conversation <ArrowUpRight size={20} /></a>}</div></div>
        <form id="message-form" className="contact-form" onSubmit={send}><div className="form-intro"><h3>{content.contact.formHeading}</h3><p>{content.contact.formIntro}</p></div><div className="form-fields"><div className="form-row"><label>Your name<input name="name" placeholder="Your full name" autoComplete="name" required maxLength={100} /></label><label>Your email<input name="email" type="email" placeholder="you@example.com" autoComplete="email" required /></label></div><label>A little about your idea<textarea name="message" placeholder="Tell me about your project or opportunity…" required minLength={10} maxLength={3000} rows={3} /></label><div className="honeypot" aria-hidden="true"><label>Leave this field empty<input name="company" type="text" tabIndex={-1} autoComplete="off" /></label></div><div className="form-submit"><span className="form-status" role="status">{status}</span><button className="button primary" type="submit" disabled={sending}>{sending ? "Sending…" : "Send message"}<Send size={16} /></button></div></div></form></section>
    </main><footer className="footer wrap"><div className="footer-top"><a className="brand" href="#">{(profile.name || "ankita").toLowerCase()}<Asterisk /></a><a href="#" className="back-top">Back to top <ArrowUpRight size={17} /></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {profile.name}. {content.footer.note}</span><div>{profile.github && <a href={profile.github} target="_blank" rel="noreferrer"><ArrowUpRight size={14} /> GitHub</a>}{profile.linkedin && <a href={profile.linkedin} target="_blank" rel="noreferrer"><ArrowUpRight size={14} /> LinkedIn</a>}</div></div></footer>
    <dialog ref={dialog} onCancel={event => { event.preventDefault(); close(); }} onClick={event => { if (event.target === event.currentTarget) close(); }} aria-labelledby="project-dialog-title"><button className="dialog-close" onClick={close} aria-label="Close project details"><X /></button>{selected && <><div className={`dialog-preview ${selected.color}`}><Preview type={selected.id} /></div><div className="dialog-content"><div className="section-label">Concept study · {selected.category}</div><h2 id="project-dialog-title">{selected.name}</h2><p>{selected.description}</p><h3>The possibilities</h3><ul>{selected.features.map(feature => <li key={feature}><ArrowUpRight size={15} />{feature}</li>)}</ul><div className="tags">{selected.stack.map(item => <span key={item}>{item}</span>)}</div><p className="dialog-note">An exploratory concept study. Implementation and live demo are not yet available.</p></div></>}</dialog></>;
}

