const fs = require('node:fs');
let page = fs.readFileSync('app/page.tsx','utf8');
page = page.replace('const [burst,setBurst] = useState(0);', 'const [burst,setBurst] = useState(0);');
page = page.replace('aria-label="Change sculpture color"', 'aria-label="Change sculpture color" aria-pressed={burst % 2 === 1}');
page = page.replace('<div className="project-grid" key={filter}>', '<div className={`project-grid ${filter === "All work" ? "is-overview" : "is-filtered"}`} key={filter}>');
page = page.replace('<span>0{projects.indexOf(project)+1} / {project.category.toUpperCase()}</span><span>CONCEPT</span>', '<span>{project.category}</span><span>Concept study</span>');
page = page.replace('<div className="project-title"><h3>{project.name}</h3><ArrowUpRight size={20}/></div><p>{project.subtitle}</p><div className="tags">{project.stack.map(item=><span key={item}>{item}</span>)}</div></article>', '<div className="project-info"><span className="project-kicker">{project.id === "campus" ? "Featured exploration" : project.category}</span><div className="project-title"><h3>{project.name}</h3></div><p>{project.subtitle}</p><p className="project-summary">{project.description}</p><div className="tags">{project.stack.map(item=><span key={item}>{item}</span>)}</div><button type="button" className="project-details" aria-label={`View ${project.name} details`} onClick={event=>{trigger.current=event.currentTarget;setSelected(project);}}>View details <ArrowUpRight size={18}/></button></div></article>');
page = page.replace('<span className="project-count" role="status">{String(visibleProjects.length).padStart(2,"0"))}', '<span className="project-count" role="status">{String(visibleProjects.length).padStart(2,"0"))}');
page = page.replace('{String(visibleProjects.length).padStart(2,"0")} EXPLORATIONS <ArrowDown size={13}/>', '{visibleProjects.length} {visibleProjects.length === 1 ? "exploration" : "explorations"}');
page = page.replace('<span className="serif">Thoughtful by design.</span></h2></div>', '<span className="serif">Thoughtful by design.</span></h2><div className="working-style"><p className="working-label">How I approach a project</p>{[{number:"01",title:"Understand the problem",text:"Ask questions before writing code."},{number:"02",title:"Build with intention",text:"Keep the experience clear and useful."},{number:"03",title:"Learn and refine",text:"Test the details. Make the next version better."}].map(step=><div className="working-step" key={step.number}><span>{step.number}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></div>)}</div></div>');
page = page.replace('My approach? Start with curiosity. Build with intention. Keep making it better.', 'I’m especially interested in the space where good engineering meets a clear, accessible user experience.');
page = page.replace('PROJECT CONCEPT / {selected.category}', 'Concept study · {selected.category}');
fs.writeFileSync('app/page.tsx',page);
let css=fs.readFileSync('app/globals.css','utf8');
css=css.replace('padding-top: 80px; padding-bottom: 75px;', 'padding-top: 64px; padding-bottom: 64px;');
css=css.replace('font-size: clamp(52px, 5.2vw, 76px);','font-size: clamp(52px, 5vw, 72px);');
css=css.replace('animation: sculpture-turn 38s linear infinite;', 'animation: sculpture-turn 44s linear infinite;');
css=css.replace('border: 6px solid #5d8ce6;', 'border: 5px solid #5d8ce6;');
fs.writeFileSync('app/globals.css',css);
