const fs = require('node:fs');
const path = 'app/page.tsx';
let page = fs.readFileSync(path, 'utf8');
page = page.replace(/<div className="art-top">.*?<\/div><div className="art-grid"\/>/, '<div className="art-top"><span><i/> Code. Create. Improve.</span></div><div className="art-grid"/>');
page = page.replace(/<div className="art-coordinate coordinate-top">.*?<\/div>/, '');
page = page.replace(/<span className="floating-cursor">.*?<\/span>/, '');
page = page.replace(/<span className="art-coordinate coordinate-bottom">.*?<\/span>/, '');
page = page.replace(/<div className="art-bottom">.*?<\/div>/, '<div className="art-bottom"><span>Click to change color <ArrowUpRight size={16}/></span></div>');
page = page.replace('MCA STUDENT · DEVELOPER IN THE MAKING','ANKITA · ASPIRING DEVELOPER');
page = page.replace(/<h1>.*?<\/h1>/, '<h1>Thoughtful code.<br/>Meaningful<br/><span className="heart-word">experiences.</span></h1>');
page = page.replace(/<p>Hey, I’m Ankita.*?<\/p>/, '<p>I’m Ankita, an MCA student exploring web development. I bring curiosity and care to building useful, intuitive digital experiences.</p>');
page = page.replace(/<div className="hero-foot">.*?<\/div>/, '<div className="hero-foot"><GraduationCap size={20}/><span>Master of Computer Applications</span></div>');
page = page.replace(/<div className="art-under">.*?<\/div>/, '');
page = page.replace(/<div className="hero-bottom">.*?<\/div>/, '');
page = page.replace(/  <div className="marquee".*?\r?\n/, '  <div className="focus-strip wrap"><span><Code2 size={20}/> Web development</span><span><Layers size={20}/> Thoughtful interfaces</span><span><Sparkles size={20}/> Continuous learning</span></div>\n');
const labels = [
 ['01 / SELECTED EXPLORATIONS','Selected work'], ['02 / THE HUMAN BEHIND THE CODE','About me'], ['03 / THE GROWING TOOLKIT','Skills & tools'], ['04 / STILL BECOMING','Education & growth'], ['05 / YOUR IDEA GOES HERE','Get in touch']
];
for (const [from,to] of labels) page = page.replace(from,to);
page = page.replace(/<span>A WORK IN PROGRESS\. JUST LIKE ME\.<\/span>|<span>HELLO AGAIN, I’M ANKITA\.<\/span>|<span>GOOD IDEAS NEED GOOD TOOLS\.<\/span>|<span><span className="status-dot"\/> OPEN TO POSSIBILITY<\/span>/g,'');
page = page.replace('Small sparks.<br/><span className="serif">Real possibilities.</span>','Ideas into <span className="serif">interfaces.</span>');
page = page.replace('A collection of ideas, experiments, and<br/>things that made me say, “let’s build it.”','A few concepts exploring better ways to connect, learn, and manage everyday life.');
page = page.replace(/<div className="projects-note">.*?<\/div>/,'<div className="projects-note"><p>These are concept studies. Completed projects and live demos will be added as my work develops.</p></div>');
page = page.replace('More than code.<br/>A different<br/><span className="serif">way of seeing.</span>','Curious by nature.<br/><span className="serif">Thoughtful by design.</span>');
page = page.replace(/<div className="about-sticker">.*?<\/div>/,'');
page = page.replace(/<span className="about-kicker">.*?<\/span>/,'');
page = page.replace(/<div className="about-bottom">.*?<\/div>/,'');
page = page.replace('A little logic.<br/><span className="serif">A lot of potential.</span>','My growing <span className="serif">toolkit.</span>');
page = page.replace('The technologies I’m exploring.<br/>And the foundations I’m building on.','The technologies I’m learning and the foundations I’m building on.');
page = page.replace('title:"The visible stuff."','title:"Frontend development"').replace('title:"Behind the scenes."','title:"Backend & data"').replace('title:"The everyday kit."','title:"Tools & fundamentals"');
page = page.replace(/<span className="skill-category">\{skill.category\}<\/span>/,'');
page = page.replace('One step.<br/>Then <span className="serif">the next.</span>','Learning with<br/><span className="serif">purpose.</span>');
page = page.replace(/<div className="journey-doodle".*?<\/div>/,'');
page = page.replace('Great things start<br/>with <span className="serif">a hello.</span>','Let’s build<br/><span className="serif">something meaningful.</span>');
page = page.replace('A project, a new opportunity, or a really good idea.<br/>Let’s see what we can make happen.','Have a project or opportunity in mind?<br/>I’d love to hear about it.');
page = page.replace('Leave a little hello.','Start a conversation.').replace('How should I call you?','Your full name').replace('It all starts with a ‘what if’…','Tell me about your project or opportunity…');
page = page.replace('<span>A LITTLE CODE. A LITTLE CREATIVITY. A LOT OF HEART.</span>','');
page = page.replace('<span>DESIGNED WITH INTENTION <Asterisk/></span>','');
page = page.replace('Ankita. Always a work in progress.','Ankita. Built with care.');
page = page.replace(', MousePointer2','');
fs.writeFileSync(path,page);
const oldCss = fs.readFileSync('app/globals.css','utf8');
const mockup = oldCss.slice(oldCss.indexOf('.mockup{'),oldCss.indexOf('.project-open{'));
fs.writeFileSync('artifacts/mockup-styles.txt',mockup);
fs.writeFileSync('app/icon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#2563eb"/><path d="M18 45L30 18h5l12 27h-7l-2-6H27l-2 6zm11-12h7l-3.5-9z" fill="white"/></svg>');
